// Class: ReadBDT_Overtrain_mega_safe
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::BDT_Overtrain_mega_safe
TMVA Release   : 4.2.0         [262656]
ROOT Release   : 5.34/36       [336420]
Creator        : bell
Date           : Fri Sep  9 15:37:45 2016
Host           : Linux buildvm-19.phx2.fedoraproject.org 4.3.5-300.fc23.x86_64 #1 SMP Mon Feb 1 03:18:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /unix/atlasvhbb/abell/mc15data7/scripts/tmvaExamples/train
Training events: 360953
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "False" [Print method-specific help message]
IgnoreNegWeightsInTraining: "True" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
NTrees: "100" [Number of trees in the forest]
MaxDepth: "4" [Max depth of the decision tree allowed]
nCuts: "100" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
AdaBoostBeta: "1.500000e-01" [Learning rate  for AdaBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "nopruning" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "3" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruneStrength: "0.000000e+00" [Pruning strength]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 6
imbalance                     imbalance                     imbalance                     imbalance                                                       'F'    [0.000412163120927,0.964831829071]
leading_pt                    leading_pt                    leading_pt                    leading_pt                                                      'F'    [0.03000000678,1.13828742504]
sub_leading_pt                sub_leading_pt                sub_leading_pt                sub_leading_pt                                                  'F'    [0.0200000144541,0.0299999695271]
delta_phi                     delta_phi                     delta_phi                     delta_phi                                                       'F'    [4.76837158203e-06,3.14159059525]
delta_r                       delta_r                       delta_r                       delta_r                                                         'F'    [0.358734428883,7.90833806992]
mlj                           mlj                           mlj                           mlj                                                             'F'    [0.0136260837317,1.30419111252]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new BDT_Overtrain_mega_safeNode
   
#ifndef BDT_Overtrain_mega_safeNode__def
#define BDT_Overtrain_mega_safeNode__def
   
class BDT_Overtrain_mega_safeNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   BDT_Overtrain_mega_safeNode ( BDT_Overtrain_mega_safeNode* left,BDT_Overtrain_mega_safeNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~BDT_Overtrain_mega_safeNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   BDT_Overtrain_mega_safeNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   BDT_Overtrain_mega_safeNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   BDT_Overtrain_mega_safeNode*   fLeft;     // pointer to the left daughter node
   BDT_Overtrain_mega_safeNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   BDT_Overtrain_mega_safeNode::~BDT_Overtrain_mega_safeNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool BDT_Overtrain_mega_safeNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool BDT_Overtrain_mega_safeNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadBDT_Overtrain_mega_safe : public IClassifierReader {

 public:

   // constructor
   ReadBDT_Overtrain_mega_safe( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadBDT_Overtrain_mega_safe" ),
        fNvars( 6 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "imbalance", "leading_pt", "sub_leading_pt", "delta_phi", "delta_r", "mlj" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadBDT_Overtrain_mega_safe() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[6];
   double fVmax[6];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[6];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<BDT_Overtrain_mega_safeNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReadBDT_Overtrain_mega_safe::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      BDT_Overtrain_mega_safeNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(BDT_Overtrain_mega_safeNode*)current->GetRight();
         else current=(BDT_Overtrain_mega_safeNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReadBDT_Overtrain_mega_safe::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.132027280648793);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0736004, 0, 1, 0.710484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.121623,-99) , 
5, 0.128973, 1, 0, 0.648061,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555744,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440021,-99) , 
4, 2.88573, 1, 0, 0.504316,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.317638,-99) , 
2, 0.0238615, 0, 0, 0.426963,-99) , 
NN(
0, 
0, 
-1, 0.0240593, 0, -1, 0.254421,-99) , 
1, 0.0391261, 0, 0, 0.33388,-99) , 
1, 0.0519463, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.11851);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.0244554, 0, 1, 0.768362,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.668732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47497,-99) , 
2, 0.0244553, 0, 0, 0.583537,-99) , 
1, 0.0736004, 0, 0, 0.682592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.136446,-99) , 
5, 0.128973, 1, 0, 0.625878,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568648,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471776,-99) , 
1, 0.0440851, 0, 0, 0.522153,-99) , 
NN(
0, 
0, 
-1, 0.0222861, 0, -1, 0.359494,-99) , 
2, 0.0252476, 0, 0, 0.431397,-99) , 
NN(
0, 
0, 
-1, 0.0240593, 0, -1, 0.273559,-99) , 
1, 0.038257, 0, 0, 0.353429,-99) , 
1, 0.0519463, 0, 0, 0.497065,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.105267);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.0994478, 1, 1, 0.783241,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.652219,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479821,-99) , 
2, 0.0226733, 0, 0, 0.607679,-99) , 
1, 0.0865928, 0, 0, 0.668931,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.151021,-99) , 
5, 0.128973, 1, 0, 0.616149,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453423,-99) , 
2, 0.0266356, 0, 0, 0.498398,-99) , 
NN(
0, 
0, 
-1, 0.0673854, 0, -1, 0.35439,-99) , 
1, 0.0378222, 0, 0, 0.432665,-99) , 
NN(
0, 
0, 
-1, 0.0415163, 0, -1, 0.279163,-99) , 
2, 0.0234653, 0, 0, 0.373707,-99) , 
1, 0.0519463, 0, 0, 0.501172,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.0909527);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0744002, 0, 1, 0.640087,-99) , 
NN(
0, 
0, 
-1, 0.0661637, 0, -1, 0.389032,-99) , 
1, 0.0481924, 0, 0, 0.532773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0761441,-99) , 
5, 0.134227, 1, 0, 0.502762,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.088169);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0247523, 0, 1, 0.683898,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552709,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422326,-99) , 
2, 0.0234655, 0, 0, 0.50751,-99) , 
NN(
0, 
0, 
-1, 0.0386458, 0, -1, 0.345427,-99) , 
5, 0.0661651, 0, 0, 0.451389,-99) , 
1, 0.0663847, 0, 0, 0.529822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0827941,-99) , 
5, 0.134227, 1, 0, 0.501191,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.0781606);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.110678, 1, 1, 0.680682,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547454,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449844,-99) , 
5, 0.0725038, 0, 0, 0.510094,-99) , 
NN(
0, 
0, 
-1, 0.0240593, 0, -1, 0.358814,-99) , 
1, 0.0381055, 0, 0, 0.460573,-99) , 
1, 0.0709328, 0, 0, 0.52479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0897406,-99) , 
5, 0.134227, 1, 0, 0.497608,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.0724859);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0246534, 0, 1, 0.675173,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530101,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411184,-99) , 
2, 0.0222774, 0, 0, 0.502696,-99) , 
NN(
0, 
0, 
-1, 0.0241583, 0, -1, 0.358166,-99) , 
1, 0.0356739, 0, 0, 0.467799,-99) , 
1, 0.0709328, 0, 0, 0.526737,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.159879,-99) , 
5, 0.125613, 1, 0, 0.495643,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.0689872);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.722293,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6291,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480494,-99) , 
5, 0.0973555, 1, 0, 0.56789,-99) , 
2, 0.0247523, 0, 0, 0.64882,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453559,-99) , 
2, 0.0266336, 0, 0, 0.487942,-99) , 
NN(
0, 
0, 
-1, 0.0425635, 0, -1, 0.354035,-99) , 
5, 0.0578067, 0, 0, 0.46079,-99) , 
1, 0.0709328, 0, 0, 0.515052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.102831,-99) , 
5, 0.134227, 1, 0, 0.490396,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.0635125);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.10854, 1, 1, 0.65428,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549011,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459216,-99) , 
3, 1.99071, 1, 0, 0.515338,-99) , 
NN(
0, 
0, 
-1, 0.0240594, 0, -1, 0.407039,-99) , 
1, 0.0408074, 0, 0, 0.473291,-99) , 
1, 0.0754809, 0, 0, 0.518049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.109372,-99) , 
5, 0.134227, 1, 0, 0.494088,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.0584816);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.09906, 1, 1, 0.68184,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473116,-99) , 
2, 0.0251485, 0, 0, 0.511283,-99) , 
NN(
0, 
0, 
-1, 0.0429687, 0, -1, 0.385413,-99) , 
5, 0.0579761, 0, 0, 0.487389,-99) , 
1, 0.0845771, 0, 0, 0.521739,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.179621,-99) , 
5, 0.125613, 1, 0, 0.49393,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.0480575);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.106529, 1, 1, 0.644067,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390251,-99) , 
5, 0.110487, 1, 0, 0.504394,-99) , 
NN(
0, 
0, 
-1, 0.0649697, 0, -1, 0.385858,-99) , 
1, 0.034458, 0, 0, 0.483931,-99) , 
1, 0.080029, 0, 0, 0.517682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.121834,-99) , 
5, 0.134227, 1, 0, 0.495284,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.0516517);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.104352, 1, 1, 0.645418,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479765,-99) , 
4, 2.58935, 1, 0, 0.519462,-99) , 
NN(
0, 
0, 
-1, 0.0578055, 0, -1, 0.434955,-99) , 
1, 0.0451302, 0, 0, 0.480593,-99) , 
1, 0.0845771, 0, 0, 0.510366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.12707,-99) , 
5, 0.134227, 1, 0, 0.48899,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0441282);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.660031,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519845,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362836,-99) , 
5, 0.115016, 1, 0, 0.508045,-99) , 
NN(
0, 
0, 
-1, 0.0426046, 0, -1, 0.399782,-99) , 
5, 0.0566126, 0, 0, 0.490624,-99) , 
1, 0.0936732, 0, 0, 0.512886,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.13291,-99) , 
5, 0.134227, 1, 0, 0.492011,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0434964);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.65006,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561812,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482664,-99) , 
1, 0.0646735, 0, 0, 0.502422,-99) , 
NN(
0, 
0, 
-1, 0.0419768, 0, -1, 0.396797,-99) , 
2, 0.0216832, 0, 0, 0.484507,-99) , 
1, 0.0936732, 0, 0, 0.506162,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.138079,-99) , 
5, 0.134227, 1, 0, 0.486204,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.0442948);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.640102,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532548,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459482,-99) , 
3, 2.30176, 1, 0, 0.511699,-99) , 
NN(
0, 
0, 
-1, 0.0394554, 0, -1, 0.421981,-99) , 
2, 0.0222772, 0, 0, 0.490856,-99) , 
1, 0.0936732, 0, 0, 0.510297,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.143337,-99) , 
5, 0.134227, 1, 0, 0.490652,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0391807);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673826,-99) , 
NN(
NN(
0, 
0, 
-1, 0.0573768, 0, 1, 0.563473,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418561,-99) , 
1, 0.0393663, 0, 0, 0.477439,-99) , 
2, 0.0276237, 0, 0, 0.496209,-99) , 
1, 0.102769, 0, 0, 0.512209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.208523,-99) , 
5, 0.125613, 1, 0, 0.488957,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0363334);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.634674,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582725,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497684,-99) , 
1, 0.0691759, 0, 0, 0.515941,-99) , 
NN(
0, 
0, 
-1, 0.0649697, 0, -1, 0.449495,-99) , 
2, 0.0242574, 0, 0, 0.486318,-99) , 
1, 0.0982213, 0, 0, 0.502619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.153895,-99) , 
5, 0.134227, 1, 0, 0.484393,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0463736);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.692344,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.407391,-99) , 
4, 0.789195, 0, 0, 0.523005,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504421,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392848,-99) , 
1, 0.0429677, 0, 0, 0.444046,-99) , 
5, 0.063776, 0, 0, 0.502188,-99) , 
1, 0.102769, 0, 0, 0.517915,-99) , 
NN(
0, 
0, 
-1, 0.132182, 1, -1, 0.273576,-99) , 
5, 0.116999, 1, 0, 0.489738,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0323758);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644478,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51231,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399752,-99) , 
5, 0.115122, 1, 0, 0.50447,-99) , 
NN(
0, 
0, 
-1, 0.042246, 0, -1, 0.416087,-99) , 
2, 0.0216832, 0, 0, 0.489585,-99) , 
1, 0.107317, 0, 0, 0.501902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.164976,-99) , 
5, 0.134227, 1, 0, 0.48469,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0343743);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.637025,-99) , 
NN(
NN(
0, 
0, 
-1, 0.0598537, 0, 1, 0.54464,-99) , 
NN(
0, 
0, 
-1, 0.0566114, 0, -1, 0.468556,-99) , 
2, 0.0276237, 0, 0, 0.485141,-99) , 
1, 0.107317, 0, 0, 0.497177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.169484,-99) , 
5, 0.134227, 1, 0, 0.48059,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0376296);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609019,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460961,-99) , 
4, 2.62683, 1, 0, 0.494628,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386565,-99) , 
4, 0.717452, 0, 0, 0.487825,-99) , 
1, 0.0982213, 0, 0, 0.50096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.174378,-99) , 
5, 0.134227, 1, 0, 0.484584,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0311111);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.640236,-99) , 
NN(
NN(
0, 
0, 
-1, 0.073632, 0, 1, 0.519761,-99) , 
NN(
0, 
0, 
-1, 0.0646286, 0, -1, 0.465971,-99) , 
2, 0.0246534, 0, 0, 0.493535,-99) , 
1, 0.107317, 0, 0, 0.504453,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.239298,-99) , 
5, 0.125613, 1, 0, 0.485053,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0344781);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63304,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42746,-99) , 
5, 0.109912, 1, 0, 0.509019,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412081,-99) , 
1, 0.0468302, 0, 0, 0.449652,-99) , 
5, 0.0646286, 0, 0, 0.493336,-99) , 
1, 0.107317, 0, 0, 0.503699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.245008,-99) , 
5, 0.125613, 1, 0, 0.484895,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0262191);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.614347,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504561,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411547,-99) , 
4, 0.77917, 0, 0, 0.497339,-99) , 
NN(
0, 
0, 
-1, 0.0317121, 0, -1, 0.422082,-99) , 
1, 0.0336025, 0, 0, 0.48802,-99) , 
1, 0.102769, 0, 0, 0.499041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.251441,-99) , 
5, 0.125613, 1, 0, 0.481166,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0341193);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.618829,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516287,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43818,-99) , 
5, 0.107694, 1, 0, 0.503074,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435657,-99) , 
1, 0.0575403, 0, 0, 0.456462,-99) , 
5, 0.0723899, 0, 0, 0.4849,-99) , 
1, 0.107317, 0, 0, 0.494778,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.256408,-99) , 
5, 0.125613, 1, 0, 0.477663,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.030467);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600702,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511823,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45733,-99) , 
3, 1.8974, 1, 0, 0.487977,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397985,-99) , 
4, 0.717452, 0, 0, 0.482303,-99) , 
1, 0.102769, 0, 0, 0.492583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.262967,-99) , 
5, 0.125613, 1, 0, 0.476201,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0272402);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.605826,-99) , 
NN(
0, 
0, 
-1, 0.860938, 0, -1, 0.482202,-99) , 
1, 0.0936732, 0, 0, 0.496016,-99) , 
NN(
0, 
0, 
-1, 0.132182, 1, -1, 0.313751,-99) , 
5, 0.116999, 1, 0, 0.475745,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0262511);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.621747,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50593,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43522,-99) , 
4, 0.860938, 0, 0, 0.499554,-99) , 
NN(
0, 
0, 
-1, 0.388213, 0, -1, 0.436656,-99) , 
2, 0.0213861, 0, 0, 0.490911,-99) , 
1, 0.102769, 0, 0, 0.501305,-99) , 
NN(
0, 
0, 
-1, 0.132182, 1, -1, 0.319646,-99) , 
5, 0.116999, 1, 0, 0.481179,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0263579);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594116,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567464,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496906,-99) , 
1, 0.0560265, 0, 0, 0.525692,-99) , 
NN(
0, 
0, 
-1, 0.0502149, 0, -1, 0.475497,-99) , 
2, 0.0278217, 0, 0, 0.485447,-99) , 
1, 0.107317, 0, 0, 0.493376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.27956,-99) , 
5, 0.125613, 1, 0, 0.478358,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0317341);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454188,-99) , 
5, 0.101068, 1, 0, 0.549863,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46294,-99) , 
5, 0.105411, 1, 0, 0.509095,-99) , 
NN(
0, 
0, 
-1, 0.0216831, 0, -1, 0.467877,-99) , 
5, 0.0812599, 0, 0, 0.485343,-99) , 
1, 0.080029, 0, 0, 0.498014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.2849,-99) , 
5, 0.125613, 1, 0, 0.483115,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0235162);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586683,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464469,-99) , 
3, 2.51949, 1, 0, 0.501255,-99) , 
NN(
0, 
0, 
-1, 0.342981, 0, -1, 0.452478,-99) , 
2, 0.0216832, 0, 0, 0.493086,-99) , 
1, 0.107317, 0, 0, 0.499884,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.291409,-99) , 
5, 0.125613, 1, 0, 0.485384,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0251121);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580969,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522958,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478384,-99) , 
4, 2.35406, 1, 0, 0.49596,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421289,-99) , 
4, 0.717452, 0, 0, 0.491277,-99) , 
1, 0.107317, 0, 0, 0.497782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.296288,-99) , 
5, 0.125613, 1, 0, 0.483824,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0238806);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59882,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435965,-99) , 
5, 0.0494473, 0, 0, 0.501451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442746,-99) , 
4, 1.00443, 0, 0, 0.494557,-99) , 
1, 0.102769, 0, 0, 0.502746,-99) , 
NN(
0, 
0, 
-1, 0.132182, 1, -1, 0.342362,-99) , 
5, 0.116999, 1, 0, 0.485233,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.023506);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442466,-99) , 
3, 2.11516, 1, 0, 0.539407,-99) , 
NN(
0, 
0, 
-1, 0.860938, 0, -1, 0.484854,-99) , 
1, 0.080029, 0, 0, 0.495527,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.306604,-99) , 
5, 0.125613, 1, 0, 0.482542,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0205336);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.274428, 0, 1, 0.548321,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506774,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435882,-99) , 
5, 0.110187, 1, 0, 0.499611,-99) , 
NN(
0, 
0, 
-1, 0.0657237, 0, -1, 0.443995,-99) , 
1, 0.0345481, 0, 0, 0.491878,-99) , 
2, 0.0284158, 0, 0, 0.499902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311624,-99) , 
5, 0.125613, 1, 0, 0.487008,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0194427);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566386,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532063,-99) , 
NN(
0, 
0, 
-1, 0.0502149, 0, -1, 0.484618,-99) , 
2, 0.0284158, 0, 0, 0.491358,-99) , 
1, 0.107317, 0, 0, 0.496758,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.316046,-99) , 
5, 0.125613, 1, 0, 0.484422,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0210362);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58019,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450848,-99) , 
4, 1.00443, 0, 0, 0.497356,-99) , 
1, 0.0845772, 0, 0, 0.51097,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504669,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444986,-99) , 
0, 0.56213, 1, 0, 0.486356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419315,-99) , 
1, 0.0385824, 0, 0, 0.469756,-99) , 
2, 0.0226733, 0, 0, 0.499637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.320264,-99) , 
5, 0.125613, 1, 0, 0.487428,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0196908);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451494,-99) , 
5, 0.09906, 1, 0, 0.536731,-99) , 
NN(
0, 
0, 
-1, 0.860938, 0, -1, 0.488493,-99) , 
1, 0.0845771, 0, 0, 0.49649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.32486,-99) , 
5, 0.125613, 1, 0, 0.484844,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0230767);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.0935268, 1, 1, 0.571713,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444182,-99) , 
4, 1.00443, 0, 0, 0.493631,-99) , 
1, 0.0748912, 0, 0, 0.51189,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508578,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438109,-99) , 
1, 0.0709328, 1, 0, 0.48901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422055,-99) , 
4, 3.95683, 1, 0, 0.474367,-99) , 
3, 2.23955, 1, 0, 0.500463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329194,-99) , 
5, 0.125613, 1, 0, 0.488874,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0166242);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579956,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502032,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451532,-99) , 
4, 0.789195, 0, 0, 0.497953,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440757,-99) , 
5, 0.0474005, 0, 0, 0.493851,-99) , 
1, 0.102769, 0, 0, 0.500528,-99) , 
NN(
0, 
0, 
-1, 0.0246533, 0, -1, 0.367858,-99) , 
5, 0.116999, 1, 0, 0.48624,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.020998);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585494,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487001,-99) , 
2, 0.0286021, 0, 0, 0.493321,-99) , 
1, 0.0845778, 0, 0, 0.508395,-99) , 
NN(
0, 
0, 
-1, 0.0579761, 0, -1, 0.473988,-99) , 
2, 0.0238614, 0, 0, 0.494508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338019,-99) , 
5, 0.125613, 1, 0, 0.483976,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0199997);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579621,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504475,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455174,-99) , 
4, 1.00443, 0, 0, 0.493709,-99) , 
1, 0.0748912, 0, 0, 0.513632,-99) , 
NN(
0, 
0, 
-1, 0.0502149, 0, -1, 0.480306,-99) , 
3, 1.67966, 1, 0, 0.497641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.342734,-99) , 
5, 0.125613, 1, 0, 0.487243,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0177938);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575642,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491968,-99) , 
0, 0.392472, 0, 0, 0.500535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457678,-99) , 
1, 0.0336025, 0, 0, 0.495191,-99) , 
1, 0.102769, 0, 0, 0.501407,-99) , 
NN(
0, 
0, 
-1, 0.0246533, 0, -1, 0.378153,-99) , 
5, 0.116999, 1, 0, 0.488196,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0151221);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57129,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530303,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497716,-99) , 
0, 0.185206, 1, 0, 0.501164,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462098,-99) , 
1, 0.0336025, 0, 0, 0.496295,-99) , 
1, 0.102769, 0, 0, 0.502083,-99) , 
NN(
0, 
0, 
-1, 0.0246533, 0, -1, 0.382346,-99) , 
5, 0.116999, 1, 0, 0.489271,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0154472);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589172,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503893,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453484,-99) , 
1, 0.0320264, 0, 0, 0.499959,-99) , 
1, 0.0982213, 0, 0, 0.507236,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45463,-99) , 
5, 0.108979, 1, 0, 0.501753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.354751,-99) , 
5, 0.125613, 1, 0, 0.49195,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0159963);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552879,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487544,-99) , 
4, 2.9415, 1, 0, 0.499278,-99) , 
1, 0.0936733, 0, 0, 0.505538,-99) , 
NN(
0, 
0, 
-1, 0.3854, 0, -1, 0.458938,-99) , 
2, 0.0213861, 0, 0, 0.499192,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.358295,-99) , 
5, 0.125613, 1, 0, 0.489813,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0159997);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568255,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470112,-99) , 
4, 0.984877, 0, 0, 0.498669,-99) , 
1, 0.0845778, 0, 0, 0.510002,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442485,-99) , 
1, 0.081494, 1, 0, 0.489816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430148,-99) , 
5, 0.0579761, 0, 0, 0.479183,-99) , 
2, 0.0234653, 0, 0, 0.498867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361981,-99) , 
5, 0.125613, 1, 0, 0.489773,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0132535);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561381,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501034,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471001,-99) , 
4, 0.917546, 0, 0, 0.497947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464503,-99) , 
1, 0.0336025, 0, 0, 0.493782,-99) , 
1, 0.102769, 0, 0, 0.498978,-99) , 
NN(
0, 
0, 
-1, 0.0246533, 0, -1, 0.393042,-99) , 
5, 0.116999, 1, 0, 0.487695,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0170036);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580074,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485954,-99) , 
1, 0.0391135, 1, 0, 0.494318,-99) , 
1, 0.0784425, 0, 0, 0.511755,-99) , 
NN(
0, 
0, 
-1, 0.108979, 1, -1, 0.483068,-99) , 
2, 0.0257425, 0, 0, 0.494589,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368764,-99) , 
5, 0.125613, 1, 0, 0.486256,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0168041);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584007,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508523,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483825,-99) , 
5, 0.0780099, 0, 0, 0.495086,-99) , 
1, 0.0982213, 0, 0, 0.502203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45932,-99) , 
5, 0.10787, 1, 0, 0.497287,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.372731,-99) , 
5, 0.125613, 1, 0, 0.489053,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0136666);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551462,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490837,-99) , 
4, 2.29581, 1, 0, 0.498364,-99) , 
1, 0.102769, 0, 0, 0.502774,-99) , 
NN(
0, 
0, 
-1, 0.401093, 0, -1, 0.463098,-99) , 
2, 0.0212871, 0, 0, 0.497772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376668,-99) , 
5, 0.125613, 1, 0, 0.48978,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0167709);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589327,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489948,-99) , 
5, 0.0882082, 0, 0, 0.496609,-99) , 
1, 0.0936732, 0, 0, 0.504602,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449211,-99) , 
4, 2.1139, 1, 0, 0.471323,-99) , 
5, 0.101217, 1, 0, 0.498416,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379882,-99) , 
5, 0.125613, 1, 0, 0.490604,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0118007);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55154,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462353,-99) , 
5, 0.0463769, 0, 0, 0.500698,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461712,-99) , 
4, 0.717452, 0, 0, 0.498309,-99) , 
1, 0.102769, 0, 0, 0.502383,-99) , 
NN(
0, 
0, 
-1, 0.0247523, 0, -1, 0.408387,-99) , 
5, 0.116999, 1, 0, 0.492425,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0129033);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582527,-99) , 
NN(
0, 
0, 
-1, 0.0318913, 0, -1, 0.496877,-99) , 
1, 0.0936732, 0, 0, 0.504247,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463049,-99) , 
4, 2.81299, 1, 0, 0.488985,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43918,-99) , 
1, 0.0813468, 1, 0, 0.470791,-99) , 
5, 0.101217, 1, 0, 0.498027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386636,-99) , 
5, 0.125613, 1, 0, 0.490706,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0134054);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579386,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463569,-99) , 
1, 0.0318913, 0, 0, 0.500103,-99) , 
1, 0.0936732, 0, 0, 0.506918,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508715,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466258,-99) , 
4, 2.81299, 1, 0, 0.488785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44236,-99) , 
1, 0.0813468, 1, 0, 0.471831,-99) , 
5, 0.101217, 1, 0, 0.500397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3897,-99) , 
5, 0.125613, 1, 0, 0.49313,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0127431);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546358,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50049,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477616,-99) , 
4, 1.00443, 0, 0, 0.497879,-99) , 
1, 0.0845772, 0, 0, 0.505724,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507118,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448067,-99) , 
0, 0.56213, 1, 0, 0.489067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446308,-99) , 
1, 0.0385824, 0, 0, 0.478553,-99) , 
2, 0.0226733, 0, 0, 0.498257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392893,-99) , 
5, 0.125613, 1, 0, 0.491348,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0124027);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54523,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495926,-99) , 
0, 0.300772, 0, 0, 0.510692,-99) , 
NN(
0, 
0, 
-1, 0.0545648, 0, -1, 0.490447,-99) , 
2, 0.0278217, 0, 0, 0.494448,-99) , 
1, 0.102769, 0, 0, 0.498322,-99) , 
NN(
0, 
0, 
-1, 0.0247523, 0, -1, 0.41733,-99) , 
5, 0.116999, 1, 0, 0.48977,-99)    );
  // itree = 57
  fBoostWeights.push_back(0.0117169);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573247,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500971,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466053,-99) , 
2, 0.0208911, 0, 0, 0.497925,-99) , 
1, 0.0936732, 0, 0, 0.504384,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46959,-99) , 
4, 2.81299, 1, 0, 0.489091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444739,-99) , 
1, 0.0813468, 1, 0, 0.472905,-99) , 
5, 0.101217, 1, 0, 0.498534,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398907,-99) , 
5, 0.125613, 1, 0, 0.492015,-99)    );
  // itree = 58
  fBoostWeights.push_back(0.0189247);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480125,-99) , 
5, 0.0945294, 1, 0, 0.54275,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514827,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487359,-99) , 
4, 4.08939, 0, 0, 0.492673,-99) , 
1, 0.0793802, 0, 0, 0.502551,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457892,-99) , 
4, 3.66545, 1, 0, 0.496163,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421739,-99) , 
0, 0.473112, 1, 0, 0.475324,-99) , 
3, 2.51949, 1, 0, 0.496707,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40172,-99) , 
5, 0.125613, 1, 0, 0.490497,-99)    );
  // itree = 59
  fBoostWeights.push_back(0.0149412);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487046,-99) , 
5, 0.0935268, 1, 0, 0.543072,-99) , 
NN(
0, 
0, 
-1, 0.789195, 0, -1, 0.495573,-99) , 
1, 0.0793802, 0, 0, 0.504935,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517279,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461827,-99) , 
5, 0.0612986, 0, 0, 0.496275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429545,-99) , 
1, 0.0663851, 1, 0, 0.475633,-99) , 
3, 2.51949, 1, 0, 0.498647,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406276,-99) , 
5, 0.125613, 1, 0, 0.492616,-99)    );
  // itree = 60
  fBoostWeights.push_back(0.0136696);
  fForest.push_back( 
NN(
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608905,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498786,-99) , 
5, 0.0885872, 1, 0, 0.539984,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501703,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464847,-99) , 
1, 0.0322223, 0, 0, 0.498282,-99) , 
1, 0.0748911, 0, 0, 0.508008,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512278,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461209,-99) , 
4, 3.66545, 1, 0, 0.494209,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429625,-99) , 
0, 0.473112, 1, 0, 0.476149,-99) , 
3, 2.51949, 1, 0, 0.501173,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409885,-99) , 
5, 0.125613, 1, 0, 0.495219,-99)    );
  // itree = 61
  fBoostWeights.push_back(0.0134987);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.0896156, 1, 1, 0.540867,-99) , 
NN(
0, 
0, 
-1, 0.789195, 0, -1, 0.495499,-99) , 
1, 0.0748911, 0, 0, 0.506076,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517502,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468854,-99) , 
5, 0.0668419, 0, 0, 0.494509,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43583,-99) , 
1, 0.0663851, 1, 0, 0.476374,-99) , 
3, 2.51949, 1, 0, 0.499705,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413196,-99) , 
5, 0.125613, 1, 0, 0.494068,-99)    );
  // itree = 62
  fBoostWeights.push_back(0.0149056);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573115,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492979,-99) , 
0, 0.344511, 0, 0, 0.501834,-99) , 
1, 0.0928475, 0, 0, 0.509548,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517648,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47223,-99) , 
5, 0.0668411, 0, 0, 0.495742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441941,-99) , 
1, 0.0663851, 1, 0, 0.479482,-99) , 
3, 2.51949, 1, 0, 0.503012,-99) , 
NN(
0, 
0, 
-1, 0.0247523, 0, -1, 0.434365,-99) , 
5, 0.116999, 1, 0, 0.495793,-99)    );
  // itree = 63
  fBoostWeights.push_back(0.0105454);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554587,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529927,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499716,-99) , 
2, 0.0288118, 0, 0, 0.502838,-99) , 
1, 0.0973366, 0, 0, 0.507942,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463395,-99) , 
4, 3.66545, 1, 0, 0.493504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439339,-99) , 
0, 0.473112, 1, 0, 0.478381,-99) , 
3, 2.51949, 1, 0, 0.501604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420099,-99) , 
5, 0.125613, 1, 0, 0.496302,-99)    );
  // itree = 64
  fBoostWeights.push_back(0.0135919);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567662,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507124,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476993,-99) , 
4, 0.789195, 0, 0, 0.504246,-99) , 
1, 0.0928475, 0, 0, 0.5111,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520151,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484059,-99) , 
1, 0.0392315, 0, 0, 0.501776,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456652,-99) , 
1, 0.0527408, 1, 0, 0.480652,-99) , 
3, 2.51949, 1, 0, 0.504483,-99) , 
NN(
0, 
0, 
-1, 0.0247523, 0, -1, 0.439958,-99) , 
5, 0.116999, 1, 0, 0.497703,-99)    );
  // itree = 65
  fBoostWeights.push_back(0.0139896);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560847,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490408,-99) , 
0, 0.366274, 0, 0, 0.498939,-99) , 
1, 0.0748912, 0, 0, 0.513057,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451915,-99) , 
5, 0.0502149, 0, 0, 0.496836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445671,-99) , 
0, 0.575806, 1, 0, 0.489949,-99) , 
3, 1.58635, 1, 0, 0.501292,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425991,-99) , 
5, 0.125613, 1, 0, 0.496401,-99)    );
  // itree = 66
  fBoostWeights.push_back(0.012194);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562726,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48376,-99) , 
4, 1.07617, 0, 0, 0.501419,-99) , 
1, 0.0793803, 0, 0, 0.513137,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501414,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456077,-99) , 
5, 0.0502149, 0, 0, 0.494691,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450724,-99) , 
0, 0.566816, 1, 0, 0.48828,-99) , 
3, 1.58635, 1, 0, 0.500481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429415,-99) , 
5, 0.125613, 1, 0, 0.495868,-99)    );
  // itree = 67
  fBoostWeights.push_back(0.00990802);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558069,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521967,-99) , 
NN(
0, 
0, 
-1, 0.0340527, 0, -1, 0.494527,-99) , 
0, 0.13116, 1, 0, 0.497335,-99) , 
1, 0.0982213, 0, 0, 0.502143,-99) , 
NN(
0, 
0, 
-1, 0.0243564, 0, -1, 0.45705,-99) , 
5, 0.108384, 1, 0, 0.494594,-99)    );
  // itree = 68
  fBoostWeights.push_back(0.00842182);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555624,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519494,-99) , 
NN(
0, 
0, 
-1, 0.0340527, 0, -1, 0.497004,-99) , 
0, 0.13116, 1, 0, 0.499305,-99) , 
1, 0.0982213, 0, 0, 0.503762,-99) , 
NN(
0, 
0, 
-1, 0.0243564, 0, -1, 0.45951,-99) , 
5, 0.108384, 1, 0, 0.496356,-99)    );
  // itree = 69
  fBoostWeights.push_back(0.0100927);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553544,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520485,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488251,-99) , 
4, 1.02359, 0, 0, 0.509912,-99) , 
NN(
0, 
0, 
-1, 0.0483395, 0, -1, 0.495941,-99) , 
4, 2.08058, 1, 0, 0.50098,-99) , 
1, 0.0982213, 0, 0, 0.505138,-99) , 
NN(
0, 
0, 
-1, 0.0243564, 0, -1, 0.461602,-99) , 
5, 0.108384, 1, 0, 0.497853,-99)    );
  // itree = 70
  fBoostWeights.push_back(0.0136725);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578276,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529656,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498966,-99) , 
5, 0.0609788, 1, 0, 0.503507,-99) , 
1, 0.0793803, 0, 0, 0.516683,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518166,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468632,-99) , 
5, 0.0525175, 0, 0, 0.50666,-99) , 
NN(
0, 
0, 
-1, 2.75663, 1, -1, 0.47788,-99) , 
1, 0.0527405, 1, 0, 0.492956,-99) , 
3, 1.58635, 1, 0, 0.504497,-99) , 
NN(
0, 
0, 
-1, 0.0248514, 0, -1, 0.453071,-99) , 
5, 0.116999, 1, 0, 0.499106,-99)    );
  // itree = 71
  fBoostWeights.push_back(0.0117195);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555631,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52066,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496699,-99) , 
5, 0.0882253, 0, 0, 0.50527,-99) , 
1, 0.0748912, 0, 0, 0.516731,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458993,-99) , 
4, 4.43319, 1, 0, 0.498338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45442,-99) , 
0, 0.575806, 1, 0, 0.492437,-99) , 
3, 1.58635, 1, 0, 0.504361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442764,-99) , 
5, 0.125613, 1, 0, 0.500373,-99)    );
  // itree = 72
  fBoostWeights.push_back(0.0109622);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552155,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497178,-99) , 
1, 0.0502642, 0, 0, 0.512331,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504446,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475814,-99) , 
5, 0.0586597, 0, 0, 0.497084,-99) , 
3, 1.18199, 1, 0, 0.50263,-99) , 
1, 0.0982213, 0, 0, 0.50654,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501567,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419612,-99) , 
2, 0.0243564, 0, 0, 0.466516,-99) , 
5, 0.108384, 1, 0, 0.499846,-99)    );
  // itree = 73
  fBoostWeights.push_back(0.0147456);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493296,-99) , 
2, 0.0249504, 0, 0, 0.549287,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530191,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498461,-99) , 
5, 0.0683223, 1, 0, 0.505666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474327,-99) , 
1, 0.0338292, 0, 0, 0.500969,-99) , 
1, 0.0729719, 0, 0, 0.514131,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514099,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471125,-99) , 
5, 0.0520906, 0, 0, 0.504082,-99) , 
NN(
0, 
0, 
-1, 2.75665, 1, -1, 0.480666,-99) , 
1, 0.0527405, 1, 0, 0.493207,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426034,-99) , 
5, 0.108384, 1, 0, 0.484064,-99) , 
3, 1.58635, 1, 0, 0.499007,-99)    );
  // itree = 74
  fBoostWeights.push_back(0.0124564);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0254454, 0, 1, 0.549583,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521742,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510057,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48676,-99) , 
5, 0.0821182, 0, 0, 0.496782,-99) , 
1, 0.0563783, 0, 0, 0.503233,-99) , 
1, 0.0729719, 0, 0, 0.515853,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480155,-99) , 
5, 0.0518479, 0, 0, 0.498952,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475708,-99) , 
3, 2.83362, 1, 0, 0.493863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429644,-99) , 
5, 0.108384, 1, 0, 0.485129,-99) , 
3, 1.58635, 1, 0, 0.500398,-99)    );
  // itree = 75
  fBoostWeights.push_back(0.014764);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0636287, 0, 1, 0.543193,-99) , 
NN(
NN(
0, 
0, 
-1, 0.503521, 0, 1, 0.510985,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449059,-99) , 
5, 0.110669, 1, 0, 0.500706,-99) , 
2, 0.0263366, 0, 0, 0.514658,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472867,-99) , 
4, 3.9757, 1, 0, 0.501438,-99) , 
NN(
0, 
0, 
-1, 2.75665, 1, -1, 0.482955,-99) , 
1, 0.0527405, 1, 0, 0.492854,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432699,-99) , 
5, 0.108384, 1, 0, 0.484677,-99) , 
3, 1.58635, 1, 0, 0.499577,-99)    );
  // itree = 76
  fBoostWeights.push_back(0.0120677);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0.0249965, 0, 1, 0.557064,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526728,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49769,-99) , 
5, 0.0637236, 1, 0, 0.502894,-99) , 
1, 0.0729719, 0, 0, 0.517587,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485225,-99) , 
1, 0.0527405, 1, 0, 0.495137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449652,-99) , 
5, 0.108384, 1, 0, 0.488937,-99) , 
3, 1.67966, 1, 0, 0.50393,-99) , 
NN(
0, 
0, 
-1, 0.398405, 0, -1, 0.46216,-99) , 
2, 0.0212871, 0, 0, 0.498736,-99)    );
  // itree = 77
  fBoostWeights.push_back(0.0132362);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0636287, 0, 1, 0.540338,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49885,-99) , 
0, 0.503521, 0, 0, 0.508448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452912,-99) , 
5, 0.110669, 1, 0, 0.499236,-99) , 
2, 0.0263366, 0, 0, 0.512727,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512109,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489104,-99) , 
4, 2.90824, 1, 0, 0.497217,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473557,-99) , 
5, 0.0502158, 0, 0, 0.493819,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439108,-99) , 
5, 0.108384, 1, 0, 0.486392,-99) , 
3, 1.58635, 1, 0, 0.499479,-99)    );
  // itree = 78
  fBoostWeights.push_back(0.00956321);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54514,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487837,-99) , 
1, 0.0339114, 0, 0, 0.507935,-99) , 
1, 0.0793803, 0, 0, 0.515001,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465888,-99) , 
4, 4.43319, 1, 0, 0.497066,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.465949,-99) , 
0, 0.575806, 1, 0, 0.492893,-99) , 
3, 1.58635, 1, 0, 0.503741,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451573,-99) , 
5, 0.125613, 1, 0, 0.500381,-99)    );
  // itree = 79
  fBoostWeights.push_back(0.00970865);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0901606, 0, 1, 0.517554,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500152,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479987,-99) , 
3, 2.83362, 1, 0, 0.495738,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457779,-99) , 
5, 0.108384, 1, 0, 0.490523,-99) , 
3, 1.58635, 1, 0, 0.503887,-99) , 
NN(
0, 
0, 
-1, 0.398405, 0, -1, 0.465492,-99) , 
2, 0.0212871, 0, 0, 0.499115,-99)    );
  // itree = 80
  fBoostWeights.push_back(0.0130058);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56459,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522605,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488268,-99) , 
4, 1.07519, 0, 0, 0.510394,-99) , 
NN(
0, 
0, 
-1, 0.0588297, 0, -1, 0.493731,-99) , 
3, 1.18199, 1, 0, 0.499617,-99) , 
1, 0.0936732, 0, 0, 0.504931,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53936,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.493718,-99) , 
2, 0.0263807, 0, 0, 0.51645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451286,-99) , 
1, 0.0557831, 0, 0, 0.494646,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435694,-99) , 
2, 0.0229703, 0, 0, 0.477744,-99) , 
5, 0.0997699, 1, 0, 0.497992,-99)    );
  // itree = 81
  fBoostWeights.push_back(0.00997442);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56139,-99) , 
NN(
NN(
0, 
0, 
-1, 0.184155, 1, 1, 0.50335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478031,-99) , 
1, 0.0318913, 0, 0, 0.501388,-99) , 
1, 0.0936732, 0, 0, 0.506292,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536127,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49697,-99) , 
2, 0.0263807, 0, 0, 0.516468,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454508,-99) , 
1, 0.0557831, 0, 0, 0.49574,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438894,-99) , 
2, 0.0229703, 0, 0, 0.479448,-99) , 
5, 0.0997699, 1, 0, 0.499443,-99)    );
  // itree = 82
  fBoostWeights.push_back(0.00926782);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552691,-99) , 
NN(
NN(
0, 
0, 
-1, 0.0691392, 0, 1, 0.509616,-99) , 
NN(
0, 
0, 
-1, 4.43248, 1, -1, 0.488588,-99) , 
3, 1.58635, 1, 0, 0.49903,-99) , 
1, 0.115943, 0, 0, 0.502395,-99) , 
NN(
0, 
0, 
-1, 0.398405, 0, -1, 0.468509,-99) , 
2, 0.0212871, 0, 0, 0.498185,-99)    );
  // itree = 83
  fBoostWeights.push_back(0.00823129);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554845,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518706,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498189,-99) , 
0, 0.128569, 1, 0, 0.500303,-99) , 
1, 0.0936732, 0, 0, 0.504888,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522943,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484349,-99) , 
2, 0.0247527, 1, 0, 0.502239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45602,-99) , 
1, 0.0813468, 1, 0, 0.485484,-99) , 
5, 0.101217, 1, 0, 0.50128,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455773,-99) , 
5, 0.125613, 1, 0, 0.498359,-99)    );
  // itree = 84
  fBoostWeights.push_back(0.00799354);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552811,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513779,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498773,-99) , 
5, 0.0882082, 0, 0, 0.501937,-99) , 
1, 0.0936732, 0, 0, 0.506212,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520889,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486405,-99) , 
2, 0.0247527, 1, 0, 0.502389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458063,-99) , 
1, 0.0813468, 1, 0, 0.486323,-99) , 
5, 0.101217, 1, 0, 0.502514,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457815,-99) , 
5, 0.125613, 1, 0, 0.499645,-99)    );
  // itree = 85
  fBoostWeights.push_back(0.00834315);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550834,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497545,-99) , 
0, 0.314396, 0, 0, 0.503093,-99) , 
1, 0.0936732, 0, 0, 0.507104,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518894,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488402,-99) , 
2, 0.0247527, 1, 0, 0.502535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460048,-99) , 
1, 0.0813468, 1, 0, 0.487137,-99) , 
5, 0.101217, 1, 0, 0.503392,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.4598,-99) , 
5, 0.125613, 1, 0, 0.500594,-99)    );
  // itree = 86
  fBoostWeights.push_back(0.0155376);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.588885,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499819,-99) , 
3, 1.83523, 1, 0, 0.549121,-99) , 
NN(
NN(
0, 
0, 
-1, 3.21263, 0, 1, 0.520066,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477731,-99) , 
4, 3.08575, 1, 0, 0.49187,-99) , 
5, 0.0664615, 1, 0, 0.499972,-99) , 
1, 0.0815661, 0, 0, 0.509742,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527654,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475365,-99) , 
1, 0.0686213, 1, 0, 0.510235,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511382,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427145,-99) , 
1, 0.0395549, 0, 0, 0.477156,-99) , 
5, 0.0689737, 0, 0, 0.497625,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441818,-99) , 
5, 0.105268, 1, 0, 0.487357,-99) , 
2, 0.0238614, 0, 0, 0.500757,-99)    );
  // itree = 87
  fBoostWeights.push_back(0.00764211);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553895,-99) , 
NN(
NN(
0, 
0, 
-1, 0.0793494, 0, 1, 0.50783,-99) , 
NN(
0, 
0, 
-1, 4.39584, 1, -1, 0.492492,-99) , 
3, 1.67967, 1, 0, 0.500547,-99) , 
1, 0.115943, 0, 0, 0.503888,-99) , 
NN(
0, 
0, 
-1, 0.397122, 0, -1, 0.4733,-99) , 
2, 0.0213861, 0, 0, 0.499786,-99)    );
  // itree = 88
  fBoostWeights.push_back(0.0147942);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.83523, 1, 1, 0.548115,-99) , 
NN(
NN(
0, 
0, 
-1, 3.21263, 0, 1, 0.516789,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486159,-99) , 
1, 0.0662485, 0, 0, 0.490616,-99) , 
5, 0.0664615, 1, 0, 0.498135,-99) , 
1, 0.0815661, 0, 0, 0.508063,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490223,-99) , 
1, 0.0514567, 1, 0, 0.509287,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50837,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431646,-99) , 
1, 0.0395549, 0, 0, 0.477216,-99) , 
5, 0.0689737, 0, 0, 0.497065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445746,-99) , 
5, 0.105268, 1, 0, 0.487627,-99) , 
2, 0.0238614, 0, 0, 0.499861,-99)    );
  // itree = 89
  fBoostWeights.push_back(0.00628438);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536349,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499645,-99) , 
0, 0.274428, 0, 0, 0.518438,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499442,-99) , 
1, 0.0845771, 0, 0, 0.503017,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505451,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461072,-99) , 
1, 0.0749289, 1, 0, 0.485906,-99) , 
5, 0.101217, 1, 0, 0.499869,-99) , 
2, 0.0284158, 0, 0, 0.5025,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462861,-99) , 
5, 0.125613, 1, 0, 0.499963,-99)    );
  // itree = 90
  fBoostWeights.push_back(0.00674025);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.0936732, 0, 1, 0.506564,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490132,-99) , 
2, 0.0247527, 1, 0, 0.503878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462731,-99) , 
1, 0.0813468, 1, 0, 0.488983,-99) , 
5, 0.101217, 1, 0, 0.503296,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464424,-99) , 
5, 0.125613, 1, 0, 0.500808,-99)    );
  // itree = 91
  fBoostWeights.push_back(0.0138667);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499701,-99) , 
3, 1.83523, 1, 0, 0.544268,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520546,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50507,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488984,-99) , 
1, 0.0412319, 1, 0, 0.494376,-99) , 
5, 0.0572229, 1, 0, 0.498513,-99) , 
1, 0.0815661, 0, 0, 0.507597,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522733,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481905,-99) , 
1, 0.0686213, 1, 0, 0.509132,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446782,-99) , 
1, 0.0459248, 0, 0, 0.476202,-99) , 
5, 0.0689737, 0, 0, 0.496584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450108,-99) , 
5, 0.105268, 1, 0, 0.488047,-99) , 
2, 0.0238614, 0, 0, 0.499751,-99)    );
  // itree = 92
  fBoostWeights.push_back(0.0116585);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.83523, 1, 1, 0.543929,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517084,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505139,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490698,-99) , 
1, 0.0570587, 0, 0, 0.495518,-99) , 
5, 0.0572229, 1, 0, 0.498927,-99) , 
1, 0.0815661, 0, 0, 0.507858,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528713,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494474,-99) , 
0, 0.382048, 1, 0, 0.507978,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502701,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438579,-99) , 
1, 0.0395549, 0, 0, 0.476687,-99) , 
5, 0.0689737, 0, 0, 0.496056,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453543,-99) , 
5, 0.105268, 1, 0, 0.488248,-99) , 
2, 0.0238614, 0, 0, 0.49999,-99)    );
  // itree = 93
  fBoostWeights.push_back(0.00677899);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549282,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499217,-99) , 
4, 3.87416, 0, 0, 0.504011,-99) , 
NN(
0, 
0, 
-1, 3.75252, 1, -1, 0.487527,-99) , 
3, 2.51949, 1, 0, 0.50053,-99) , 
1, 0.115943, 0, 0, 0.503573,-99) , 
NN(
0, 
0, 
-1, 0.398405, 0, -1, 0.475438,-99) , 
2, 0.0212871, 0, 0, 0.500085,-99)    );
  // itree = 94
  fBoostWeights.push_back(0.0113035);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.83523, 1, 1, 0.5413,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53063,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498763,-99) , 
4, 3.21263, 0, 0, 0.51124,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489395,-99) , 
4, 2.38717, 1, 0, 0.496024,-99) , 
5, 0.0664615, 1, 0, 0.500395,-99) , 
1, 0.0815661, 0, 0, 0.508509,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519601,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488388,-99) , 
0, 0.523471, 1, 0, 0.509803,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50103,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442729,-99) , 
1, 0.0395549, 0, 0, 0.477391,-99) , 
5, 0.0689737, 0, 0, 0.497457,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457321,-99) , 
5, 0.105268, 1, 0, 0.490088,-99) , 
2, 0.0238614, 0, 0, 0.501118,-99)    );
  // itree = 95
  fBoostWeights.push_back(0.0107699);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497613,-99) , 
3, 1.83523, 1, 0, 0.538492,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499091,-99) , 
4, 2.88832, 0, 0, 0.511855,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492619,-99) , 
1, 0.0391898, 1, 0, 0.49627,-99) , 
5, 0.0664615, 1, 0, 0.500746,-99) , 
1, 0.0815661, 0, 0, 0.508232,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498,-99) , 
4, 2.10097, 1, 0, 0.508753,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453881,-99) , 
1, 0.0459248, 0, 0, 0.476851,-99) , 
5, 0.0689737, 0, 0, 0.496602,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460128,-99) , 
5, 0.105268, 1, 0, 0.489907,-99) , 
2, 0.0238614, 0, 0, 0.50088,-99)    );
  // itree = 96
  fBoostWeights.push_back(0.0066934);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546904,-99) , 
NN(
NN(
0, 
0, 
-1, 0.0287922, 0, 1, 0.505414,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.460236,-99) , 
4, 3.75252, 1, 0, 0.490303,-99) , 
3, 2.51949, 1, 0, 0.502222,-99) , 
1, 0.115943, 0, 0, 0.505007,-99) , 
NN(
0, 
0, 
-1, 0.398405, 0, -1, 0.477897,-99) , 
2, 0.0212871, 0, 0, 0.501648,-99)    );
  // itree = 97
  fBoostWeights.push_back(0.00850018);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566285,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51843,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482764,-99) , 
5, 0.0726967, 1, 0, 0.49296,-99) , 
1, 0.0546919, 0, 0, 0.501358,-99) , 
0, 0.46535, 0, 0, 0.51575,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481149,-99) , 
4, 0.860938, 0, 0, 0.501945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486896,-99) , 
5, 0.054565, 0, 0, 0.499929,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457178,-99) , 
5, 0.116999, 1, 0, 0.49561,-99) , 
2, 0.0273267, 0, 0, 0.500559,-99)    );
  // itree = 98
  fBoostWeights.push_back(0.00880363);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564196,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516307,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503856,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484887,-99) , 
5, 0.0726967, 1, 0, 0.493218,-99) , 
1, 0.0546919, 0, 0, 0.500831,-99) , 
0, 0.46535, 0, 0, 0.514872,-99) , 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484847,-99) , 
5, 0.0692384, 0, 0, 0.505426,-99) , 
NN(
0, 
0, 
-1, 0.567522, 1, -1, 0.494828,-99) , 
4, 2.08058, 1, 0, 0.498742,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459288,-99) , 
5, 0.116999, 1, 0, 0.494757,-99) , 
2, 0.0273267, 0, 0, 0.4997,-99)    );
  // itree = 99
  fBoostWeights.push_back(0.0048593);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534193,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0.108572, 0, 1, 0.50267,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464971,-99) , 
5, 0.120177, 1, 0, 0.500197,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466058,-99) , 
0, 0.604037, 1, 0, 0.498234,-99) , 
1, 0.117785, 0, 0, 0.500348,-99)    );
   return;
};
 
// Clean up
inline void ReadBDT_Overtrain_mega_safe::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReadBDT_Overtrain_mega_safe::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
